export const Filters = [
    { label: "action" },
    { label: "adventure" },
    { label: "comedy" },
    { label: "drama" },
    { label: "fantasy" },
    { label: "historical fiction" },
    { label: "horror" },
    { label: "mystery" },
    { label: "romance" },
    { label: "science fiction" },
    { label: "thriller" },
    { label: "western" },
    { label: "crime" },
    { label: "biography" },
    { label: "self-help" },

    { label: "drama" },
    { label: "fantasy" },
    { label: "historical fiction" },
    { label: "horror" },
    { label: "mystery" },
    { label: "romance" },
    { label: "science fiction" },
    { label: "thriller" },
    { label: "western" },
    { label: "crime" },
    { label: "biography" },
    { label: "self-help" },
];
